package mysql

var SchemaStatements = []string{
	`CREATE TABLE IF NOT EXISTS feedback (
		id VARCHAR(64) PRIMARY KEY,
		request_id VARCHAR(128) NOT NULL,
		session_id VARCHAR(128) NOT NULL,
		rating VARCHAR(16) NOT NULL,
		reason_tags LONGTEXT NOT NULL,
		` + "`comment`" + ` TEXT NOT NULL,
		corrected_answer LONGTEXT NOT NULL,
		answer_snapshot LONGTEXT NOT NULL,
		evidence_ids LONGTEXT NOT NULL,
		tool_runs LONGTEXT NOT NULL,
		metadata LONGTEXT NOT NULL,
		created_at TIMESTAMP(6) NOT NULL,
		INDEX idx_feedback_request_id (request_id),
		INDEX idx_feedback_session_id (session_id),
		INDEX idx_feedback_created_at (created_at)
	) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS eval_cases (
		id VARCHAR(64) PRIMARY KEY,
		feedback_id VARCHAR(64) NULL,
		case_type VARCHAR(32) NOT NULL,
		input_message LONGTEXT NOT NULL,
		expected_behavior LONGTEXT NOT NULL,
		gold_answer LONGTEXT NOT NULL,
		forbidden_patterns LONGTEXT NOT NULL,
		metadata LONGTEXT NOT NULL,
		created_at TIMESTAMP(6) NOT NULL,
		INDEX idx_eval_cases_feedback_id (feedback_id),
		INDEX idx_eval_cases_case_type_created_at (case_type, created_at)
	) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS eval_runs (
		id VARCHAR(64) PRIMARY KEY,
		case_type VARCHAR(32) NOT NULL,
		status VARCHAR(32) NOT NULL,
		total INT NOT NULL,
		passed INT NOT NULL,
		failed INT NOT NULL,
		created_at TIMESTAMP(6) NOT NULL,
		completed_at TIMESTAMP(6) NULL,
		INDEX idx_eval_runs_case_type_created_at (case_type, created_at)
	) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS eval_case_results (
		id VARCHAR(64) PRIMARY KEY,
		run_id VARCHAR(64) NOT NULL,
		case_id VARCHAR(64) NOT NULL,
		passed BOOLEAN NOT NULL,
		failure_reasons LONGTEXT NOT NULL,
		request_id VARCHAR(128) NOT NULL,
		trace_id VARCHAR(64) NOT NULL,
		duration_ms BIGINT NOT NULL,
		created_at TIMESTAMP(6) NOT NULL,
		INDEX idx_eval_case_results_run_id (run_id),
		INDEX idx_eval_case_results_case_id (case_id)
	) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS long_term_memories (
		id VARCHAR(64) PRIMARY KEY,
		source_type VARCHAR(32) NOT NULL,
		source_id VARCHAR(64) NOT NULL,
		service VARCHAR(128) NOT NULL,
		title VARCHAR(255) NOT NULL,
		summary TEXT NOT NULL,
		evidence_ids JSON NOT NULL,
		tags JSON NOT NULL,
		metadata JSON NOT NULL,
		created_at TIMESTAMP(6) NOT NULL,
		updated_at TIMESTAMP(6) NOT NULL,
		UNIQUE KEY uk_long_term_memory_source (source_type, source_id),
		INDEX idx_long_term_memory_service_updated (service, updated_at),
		INDEX idx_long_term_memory_updated_at (updated_at)
	) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS user_profiles (
		user_id VARCHAR(128) PRIMARY KEY,
		display_name VARCHAR(128) NOT NULL,
		default_service VARCHAR(128) NOT NULL,
		services JSON NOT NULL,
		timezone VARCHAR(64) NOT NULL,
		preferences JSON NOT NULL,
		metadata JSON NOT NULL,
		created_at TIMESTAMP(6) NOT NULL,
		updated_at TIMESTAMP(6) NOT NULL,
		INDEX idx_user_profiles_default_service (default_service),
		INDEX idx_user_profiles_updated_at (updated_at)
	) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`,
}
